// Content for the WC/OS portfolio. Edit these to update the site.

const FLAGS = [
  { flag: "CTF{h34d3rs_n3v3r_l13}", name: "Read the logs", hint: "A blog post pastes a command with more in its output than it lets on.", pts: 100 },
  { flag: "CTF{4ppl0ck3r_1s_n0t_4v}", name: "Watch to the end", hint: "One video description says more than the video does.", pts: 100 },
  { flag: "CTF{gu3stb00k_v1s1t0r}", name: "Someone signed it", hint: "A visitor left more than a compliment.", pts: 150 },
  { flag: "CTF{sud0_w4s_l0gg3d}", name: "Escalate politely", hint: "Ask the terminal for permission you do not have.", pts: 200 },
  { flag: "CTF{r3v_12_pr1nt3d}", name: "Check the metadata", hint: "The résumé was printed from something. Look at the small print.", pts: 250 }
];

const VIDEOS = [
  { title: "Hardening a Windows box: LAPS, AppLocker and the registry keys nobody mentions", length: "18:42", views: "42K views", date: "2 weeks ago",
    desc: "A full pass over a fresh Windows 11 install: local admin handling with LAPS, an AppLocker baseline that will not break your users, and the handful of registry keys worth changing by hand. Lab files and the baseline XML are linked below — pinned comment code CTF{4ppl0ck3r_1s_n0t_4v}.",
    tags: ["#windows", "#hardening", "#applocker"] },
  { title: "Subnetting explained with a whiteboard and no maths panic", length: "24:05", views: "128K views", date: "1 month ago",
    desc: "The mental model I use for subnetting, worked through slowly with real examples. No memorising tables.", tags: ["#networking", "#ccna"] },
  { title: "I broke into my own home lab — here is the whole kill chain", length: "31:17", views: "76K views", date: "1 month ago",
    desc: "Initial access to domain admin in one lab, mapped to ATT&CK at every step, then the detections that would have caught me.", tags: ["#redteam", "#attack"] },
  { title: "Linux permissions: the one diagram that fixed it for me", length: "12:38", views: "94K views", date: "2 months ago",
    desc: "Owner, group, other, and the special bits. Plus the three commands I run when something is inexplicably denied.", tags: ["#linux", "#basics"] },
  { title: "Phishing email teardown, live", length: "16:20", views: "51K views", date: "2 months ago",
    desc: "Reading raw headers, checking SPF and DKIM, sandboxing the attachment, writing the verdict up for a manager.", tags: ["#soc", "#email"] },
  { title: "Build a detection lab for under £200", length: "22:54", views: "63K views", date: "3 months ago",
    desc: "Hardware choices, hypervisor setup, and a Sysmon plus SIEM pipeline you can rebuild in an afternoon.", tags: ["#homelab", "#siem"] }
];

const POSTS = [
  { title: "Why your first SOC job will not look like the courses", meta: "12 AUG 2026 · 7 MIN",
    body: [
      "The gap between training material and a real security operations centre is mostly about volume and ambiguity. Courses give you one alert with one answer. A shift gives you two hundred alerts, most of which are noise generated by your own estate.",
      "What actually carries you through the first six months is not tool knowledge. It is the habit of writing down what you checked, in order, so that the next person can pick your work up mid-thought. Everything else is learnable on the job.",
      "If you are preparing now, practise the boring part: take one alert a day from a home lab, triage it end to end, and write a three-paragraph verdict. Do that for a month and you will interview better than someone with two more certificates."
    ],
    code: ["$ grep -i 'failed password' /var/log/auth.log | awk '{print $11}' | sort | uniq -c | sort -rn | head", "  412 203.0.113.44", "   88 198.51.100.7", "   17 CTF{h34d3rs_n3v3r_l13}"] },
  { title: "A reading list for people moving from IT support into security", meta: "29 JUL 2026 · 5 MIN",
    body: ["Support work is the best on-ramp into security and it is chronically undersold. You already know how estates break.",
      "This list is short on purpose: two books, one blog, one lab. Finish them before adding more."],
    code: ["$ ls ~/reading", "attack-notes.md   networking.md   soc-playbook.md"] },
  { title: "Group Policy is not scary, it is just badly documented", meta: "14 JUL 2026 · 9 MIN",
    body: ["Most GPO confusion comes from precedence, not syntax. Once you can predict which policy wins, the console stops fighting you.",
      "Below is the resolution order I sketch for every student, plus the one command that ends most arguments."],
    code: ["PS> gpresult /h report.html", "PS> Get-GPOReport -All -ReportType Xml | Out-File all-gpos.xml"] },
  { title: "What I changed after failing my first pentest report review", meta: "02 JUL 2026 · 6 MIN",
    body: ["The findings were fine. The report was unreadable by anyone who had to fund the fixes.",
      "Now I write the executive summary first, before touching evidence, and let the technical detail hang off it."],
    code: ["# structure that survived review", "1. impact  2. evidence  3. fix  4. cost"] },
  { title: "Notes from building the BitNye lab rack", meta: "18 JUN 2026 · 8 MIN",
    body: ["Three mini PCs, a managed switch and a lot of patience. The point of the rack is repeatability: every lesson has to be rebuildable from scratch.",
      "Full parts list and the provisioning scripts are linked at the end of the networking series."],
    code: ["$ terraform apply -auto-approve", "wc-lab: 3 nodes provisioned in 94s"] }
];

const FILES = {
  "": ["about.txt", "resume.pdf", "blog/", "videos/", "contact.txt", "top-secret/"],
  "/top-secret": ["ctf.sh*", "flags.md.gpg"],
  "/blog": ["soc-job.md", "reading-list.md", "group-policy.md", "pentest-report.md", "lab-rack.md"],
  "/videos": ["hardening-windows.mp4", "subnetting.mp4", "kill-chain.mp4", "permissions.mp4"]
};

const ROLES = [
  { role: "Security Analyst", org: "Managed detection provider", years: "2023 — now", body: "Triage and detection engineering across a mixed Windows and Linux estate. Built the phishing triage playbook now used by the whole shift." },
  { role: "IT Systems Administrator", org: "Regional healthcare group", years: "2020 — 2023", body: "Owned patching, Group Policy and network segmentation for 900 endpoints. Led the migration off flat VLANs." },
  { role: "IT Support Technician", org: "MSP", years: "2019 — 2020", body: "First line to third line across 40 client sites. Where the habit of documenting everything started." }
];

const SKILLS = ["Windows", "Active Directory", "Linux", "Bash", "PowerShell", "Networking", "Wireshark", "SIEM", "MITRE ATT&CK", "Sysmon", "Python", "Terraform"];

const CERTS = [
  { name: "CompTIA Security+", year: "2024" }, { name: "Cisco CCNA", year: "2023" },
  { name: "RHCSA", year: "2022" }, { name: "BTL1 — Blue Team Level 1", year: "2024" }
];

const LINKS = [
  { kind: "youtube", value: "youtube.com/@bitnye", href: "https://youtube.com/@bitnye" },
  { kind: "email", value: "hello@bitnye.dev", href: "mailto:hello@bitnye.dev" },
  { kind: "linkedin", value: "/in/williamcarr", href: "https://linkedin.com/in/williamcarr" },
  { kind: "github", value: "github.com/bitnye", href: "https://github.com/bitnye" }
];

const GUESTS_SEED = [
  { name: "marcus_t", when: "2 DAYS AGO", text: "The subnetting video is the only one that ever made it click. Passed CCNA last week." },
  { name: "priya", when: "5 DAYS AGO", text: "Please do a full detection engineering path. Would pay for it." },
  { name: "hexdump", when: "1 WEEK AGO", text: "Found the terminal, and the folder you forgot to hide. Have one back: CTF{gu3stb00k_v1s1t0r}. Try 'sudo' next." },
  { name: "jenna_ops", when: "2 WEEKS AGO", text: "Sent the Group Policy post to my whole team. Precedence diagram is on our wall now." }
];

const TIPS = [
  { n: "01", title: "Dock", body: "Every app is one click away along the bottom." },
  { n: "02", title: "Desktop", body: "Click an icon on the left to open it in a window." },
  { n: "03", title: "Windows", body: "Drag titlebars, stack them, keep several open at once." },
  { n: "04", title: "Terminal", body: "Press ` and browse the whole site by command." }
];
